### ISSUE TITLE
Resolve hostname set in ssh config

### ISSUE THREAD

**Issue by G0V1NDS** [linrongbin16/gitlinker.nvim#87]
Original issue in upstream repo: https://github.com/ruifm/gitlinker.nvim/issues/53

Working PR for the same in upstream repo: https://github.com/ruifm/gitlinker.nvim/pull/52 (Pending review)

**Comment by linrongbin16** [comment]
hi, @G0V1NDS, thanks for mention it, I'm looking into it.

**Comment by linrongbin16** [comment]
would you please help me with some details:

1. when mention `alias`, can you give a specific case? if it's not data-sensitive.
2. you propose using `ssh -G` to resolve host, I need to check how does the command work, if it's a better way to resolve all git remotes, or just for your use case?

**Comment by G0V1NDS** [comment]
@linrongbin16 
I just referred open issue from upstream repo. Upstream issue and PR were created by @joaodubas

I will explain how I am using ssh config. SSH allows you to configure alias for the hosts. 
For example I have this alias in my ~/.ssh/config:
```sshconfig
Host github-personal
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_rsa_personal
    Compression no
```

I can use this alias in git remote like this:
```shell
# ❯ git remotes
origin  https://github.com/G0V1NDS/dotfiles-open.git (fetch)
origin  https://github.com/G0V1NDS/dotfiles-open.git (push)
personal        git@github-personal:G0V1NDS/dotfiles-open.git (fetch)
personal        git@github-personal:G0V1NDS/dotfiles-open.git (push)
```
Here `origin` remote is configured from regular https URL provided when cloning the repo. I configured another origin named `personal` using `github-personal` alias.
Now when I push to `personal` remote, git internally resolves this alias and understands that `github-personal` is pointing to `github.com` and it has to use `~/.ssh/id_rsa_personal` key.

We can get the same info from `ssh -G` by checking the config for the configured host. 
Like this:
```
# ❯ ssh -G github-personal | grep ^hostname
hostname github.com
```

Not sure `ssh -G` is the best approach available, got to know about this from original issue only, but I can see that is will solve a generic problem and not limited to my use case.

**Comment by linrongbin16** [comment]
I will first do some investigation into this, make sure the solution is good for most users.

**Comment by linrongbin16** [comment]
Hi @G0V1NDS , @joaodubas,

Please use below config to map `github-personal.com` to `github.com`:


```lua
require("gitlinker").setup({
    custom_rules = function(remote_url)
        local rules = {
            {
                "^git@github-personal%.([_%.%-%w]+):([%.%-%w]+)/([_%.%-%w]+)%.git$",
                "https://github.%1/%2/%3/blob/",
            },
            {
                "^git@github-personal%.([_%.%-%w]+):([%.%-%w]+)/([_%.%-%w]+)$",
                "https://github.%1/%2/%3/blob/",
            },
        }
        for _, rule in ipairs(rules) do
            local pattern = rule[1]
            local replace = rule[2]
            if string.match(remote_url, pattern) then
                local result = string.gsub(remote_url, pattern, replace)
                return result
            end
        end
        return nil
    end,
})
```

**Comment by G0V1NDS** [comment]
@linrongbin16 Thanks for a quick solution, really appreciate it. 
I was able to achieve the expected result from the `override_rules` with some tweaks on your suggestion.
```
    override_rules = {
      {
        "^git@github%-personal:([%.%-%w]+)/([_%.%-%w]+)$",
        "https://github.com/%1/%2/blob/",
      },
      {
        "^git@bitbucket%-work:([%.%-%w]+)/([_%.%-%w]+)$",
        "https://bitbucket.org/%1/%2/src/",
      },
      {
        "^git@gitlab%-work:([%.%-%w]+)/([_%.%-%w]+)$",
        "https://gitlab.com/%1/%2/blob/",
      },
    },
```

Tweaks made: 
- My ssh alias wasn't having TLD suffix, so I had to hardcode it in substitute pattern.
- Needed to escape the hyphen in the pattern `%-personal` to ensure proper functionality.

I would still prefer a solution which utilises the ssh config so user won't need to define a override rule as the information is already available in ssh config. 
Will see how [fugitive](https://github.com/tpope/vim-fugitive) is achieving the host identification for ssh remotes.

**Comment by G0V1NDS** [comment]
@linrongbin16 A quick look at [fugitive code](https://github.com/tpope/vim-fugitive/blob/46eaf8918b347906789df296143117774e827616/autoload/fugitive.vim#L1272) tells that it is achieving the same by reading the ssh config file to read information ('user', 'hostname' and 'port') which helps derive the remote url.

**Comment by linrongbin16** [comment]
hi @G0V1NDS , thanks for point that out, I will check

**Comment by joaodubas** [comment]
@linrongbin16 the solution I implemented in a PR upstream parses the result [`ssh -G <alias>`][0], as can be seen in [`lua/gitlinker/ssh.lua`][1].

I can open the same PR here if it makes sense.

[0]: https://man.openbsd.org/ssh#G
[1]: https://github.com/ruifm/gitlinker.nvim/blob/c8f04b1d992a84f2f5dbac8fdf286c902fedb730/lua/gitlinker/ssh.lua#L30

**Comment by linrongbin16** [comment]
yeah, @joaodubas  thank you!

I just found this thing is much more complicated, seems using ssh is the correct way to get the domain

**Comment by linrongbin16** [comment]
@joaodubas , oh, I forgot why this [lua/gitlinker/ssh.lua](https://github.com/ruifm/gitlinker.nvim/blob/c8f04b1d992a84f2f5dbac8fdf286c902fedb730/lua/gitlinker/ssh.lua#L30) not in my fork (maybe at first I didn't know what this `ssh` is for, so I simply delete it?)

I will patch this part back to my fork. thanks for point that!

**Comment by joaodubas** [comment]
@linrongbin16 this is the module I created to solve the issue with aliases in `ssh` configuration. It belongs to the PR @G0V1NDS referenced on the first message (ruifm#53)

**Comment by linrongbin16** [comment]
hi @joaodubas , the PR https://github.com/ruifm/gitlinker.nvim/pull/52 seems not existed in https://github.com/ruifm/gitlinker.nvim latest master now.

I'm trying to add `ssh -G host` in this PR: https://github.com/linrongbin16/gitlinker.nvim/pull/110.

But I have some issue when testing it in my local machine.

Here's my testing steps (not sure if there's any issue):

1. set my `~/.ssh/config`:

   ```
   Host github-personal.com
       HostName github.com
       User git
       IdentityFile ~/.ssh/id_rsa_personal
       Compression no
   ```

2. set my `~/github/linrongbin16/gitlinker.nvim/.git/config`:

   ```
   ```

**Comment by G0V1NDS** [comment]
@linrongbin16 your ssh and git config looks good to me.
I tried testing the code on local and faced multiple issues except the `rev-parse` issue, added the fix for those in PR comments.

**Comment by linrongbin16** [comment]
really thanks for your contribute!

I have fixed all the comments in:
- https://github.com/linrongbin16/gitlinker.nvim/commit/2aa1d7389e9668f924023ee85934dc8ae32fc805  - https://github.com/linrongbin16/gitlinker.nvim/commit/e8368aea817256a5bd5c3b6b677a1731363ce69f


would you please take a look again?

**Comment by G0V1NDS** [comment]
@linrongbin16 All the issues are resolved, thanks for quick update.
Tested for github mainly, everything looks good. 
Though BitBucket is not officially supported, still tried the same on a BitBucket repo. URL format was almost same, I just replaced `blob` with `src` in URL and it worked for BitBucket too.

Were you able to fix your local issue regarding `rev-parse`?

**Comment by linrongbin16** [comment]
No, I still failed to generate the git link in my local environment, but since you helped testing, I will merge into master branch now.

really thanks to your contribute!

**Comment by linrongbin16** [comment]
solved
